apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-gvby
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/susdas_quay_org/mvp-dev-bzml-tenant/mvp-test-app/test-mvp-component-gvby@sha256:c8def7b1f893bcf5932e9ef1bc07451d67b6ee55ad21dd4b81df919b676645cd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
